---
- name: Install autojump
  become: true
  community.general.pacman:
    name: autojump
    state: present
  
- name: Add autojump plugin to zsh config file
  ansible.builtin.replace:
    path: "{{ '/home/' + user + '/.zshrc' if user != 'root' else '/root/.zshrc' }}"
    regexp: '^(plugins=\(.*)(\))$'
    replace: '\1 autojump\2'
