---
- name: Install Neovim
  become: true
  pacman:
    name: neovim
    state: present

- name: Clone Neovim configuration
  become: false
  git:
    repo: "{{ neovim_config_repo }}"
    dest: "{{ '/home/' + user + '/.config/nvim' if user != 'root' else '/root/.config/nvim' }}"
    clone: yes
    update: yes

- name: deps
  pacman:
    name: 
      - ripgrep
    state: present

