---
- name: Install Neovim
  become: true
  pacman:
    name: neovim
    state: present

- name: Clone Neovim configuration
  become: false
  git:
    repo: https://github.com/amkarkhi/kickstart-nvim.git
    dest: "{{ '/home/' + user + '/.config/nvim' if user != 'root' else '/root/.config/nvim' }}"
    clone: yes
    update: yes

- name: deps
  pacman:
    name: 
      - ripgrep
    state: present

