---
python_required_stuff: 
  - python
  - python-pip
  - python-virtualenv

required_packages:
  - make
  - base-devel
  - openssl
  - zlib
  - bzip2
  - readline
  - sqlite
  - wget
  - curl
  - ncurses
  - xz
  - tk
  - libffi
  - xz-utils
  - ca-certificates
  - gnupg
  - tree
  - git
  - cmake
  - libxcb
  - xorg-xkbcomp
  - python-setuptools
