---
- name: Update package list
  become: true
  community.general.pacman:
    update_cache: yes

- name: Install required Python stuffs
  become: true
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-virtualenv
  notify: 
    - Install pipenv

- name: Install Pyenv required packages
  become: true
  community.general.pacman:
    update_cache: yes
    name:
      - base-devel
      - openssl
      - zlib
      - bzip2
      - readline
      - sqlite
      - wget
      - curl
      - ncurses
      - xz
      - tk
      - libffi
  notify:
    - Install pyenv
