---
- name: Install Docker package
  become: true
  pacman:
    name: docker
    state: present

- name: Enable and start Docker service
  become: true
  systemd:
    name: docker
    state: started
    enabled: yes
  register: docker_status

- name: Print Docker service status
  debug:
    var: docker_status

