---
- include_tasks: telegram.yml
  tags: 
    - desktop
- include_tasks: monitoring-packages.yml
  tags:
    - devops
- include_tasks: v2ray-plugin.yml
  tags:
    - devops
- include_tasks: shadowsocks.yml
  tags:
    - devops
- include_tasks: kubectl.yml
  tags:
    - devops
- include_tasks: docker.yml
  tags:
    - devops
- include_tasks: open-ssh.yml
  tags:
    - devops
- include_tasks: vlc.yml
  tags:
    - desktop
# - include_task: warp.yml
#   tags:
#     - shell
# - include_task: persepolis.yml
#   tags:
#     - shell
# - include_task: firefox.yml
#   tags:
#     - shell

