---
- name: Download warp-plus
  ansible.builtin.get_url:
    url: https://github.com/bepass-org/warp-plus/releases/download/v1.1.3/warp-plus_linux-arm64.zip
    dest: /tmp/warp-plus_linux-arm64.zip

- name: Extract warp-plus
  ansible.builtin.unarchive:
    src: /tmp/warp-plus_linux-arm64.zip
    dest: /.tools/
    remote_src: yes

- name: Add alias to shell config
  ansible.builtin.lineinfile:
    path: "{{ '/home/' + user + '/.zshrc' if user != 'root' else '/root/.zshrc' }}"
    line: alias warp='/.tools/warp-plus/warp'
    insertafter: EOF

